# Generated by Django 4.2.11 on 2024-11-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0002_session_user_remove_question_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="useranswer", name="answers",),
        migrations.AddField(
            model_name="useranswer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="正解かどうか"),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizapp.question",
                verbose_name="問題",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_option",
            field=models.CharField(default="", max_length=255, verbose_name="選択肢"),
        ),
    ]
